all: step1.c step3.c step5.c step6.c step7.c step8.c
	gcc -o 1 step1.c
	gcc -o 3 step3.c
	gcc -o 5 step5.c 
	gcc -o 6 step6.c
	gcc -o 7 step7.c
	gcc -o 8 -lpthread step8.c 

clean:; rm -f 1 3 5 6 7 8
